# -*- coding: utf-8 -*-
"""Apply final-sweep corrections (6 entries across 3 sector files)."""
import json, sys
from pathlib import Path
sys.stdout.reconfigure(encoding='utf-8')

BASE = Path(r"c:\Users\Sahal Saeed\Documents\tempest_ai\quick\New_quick\new_quick\quite_change\data")

# Corrections grouped by sector
PET = {}
MAR = {}
LT  = {}

# === Petroleum ===
PET["5019"] = {"jp": """**会社概要:** 出光興産(5019)は日本第2位の石油精製・販売会社 — 国内のガソリンスタンドのシェア約30%を持ち、製油所を北海道・千葉・愛知・徳山に展開。 加えて『高機能材セグメント』として、有機EL青色発光材料(スマホ・テレビのディスプレイ用)、リチウムイオン電池材料、潤滑油の海外販売など、独自の成長軸を持つ多角化エネルギー企業。 簡単に言えば、『石油精製を主力にしながら、ハイテク向けの高機能材料事業も育てている総合エネルギー会社』。

**業績の動き:** 2026年3月期の第3四半期累計(4-12月)は、売上高¥5兆9,446億円(-13.6%)、営業利益¥367億円(-70.2%)、経常利益¥549億円(-66.8%)、親会社株主に帰属する当期純利益¥525.78億円(-58.75%)と、売上・利益とも大きく減少しました。 燃料油セグメントの業績悪化が主因で、高機能材セグメントは好調を維持。 通期予想は据え置きで、引き続き厳しい事業環境が続く見通しです。 前期(2025年3月期)はコスト管理を通じて営業利益+30.84%の増益を達成しましたが、今期はその反動で利益が大きく落ち込んでいます。

**なぜ業績がこう動いたのか:** 業績悪化の最大の要因は燃料油セグメントの大幅減益です。 出光の利益の一定部分は『在庫評価のタイムラグ効果』(原油価格の変動が時間差で利益に影響)に依存しているため、原油価格の動向で業績が振れる構造を持ちます。 今期は原油価格が下落局面に入り、保有原油在庫の評価益が縮小したことに加え、大型定期修繕によるコスト増も重なり、燃料油セグメントの利益が大きく圧迫されました。 一方で、高機能材セグメント(有機EL青色発光材料、リチウム電池材料など)は好調を維持。 潤滑油の海外販売も伸長しています。 ただし、高機能材セグメントの規模はまだ小さく、燃料油の落ち込みを補うには至っていません。

**なぜ株価がこう動いたのか:** 株価が動いた主な理由は3つ。 1つ目は業績悪化を市場が織り込んだ — 営業利益-70.2%という大幅減益は、株価の下押し要因。 2つ目は原油価格依存の構造的なリスクへの警戒 — 在庫評価効果に左右される構造的脆さが、市場で意識されています。 3つ目はESG投資家のスクリーン — 化石燃料関連株の保有を限定する機関投資家(特にヨーロッパ系のESGファンド)は、業績改善があっても買い増しに踏み込まないため、株価の上値が抑えられています。 一方で、出光はPBR改善策(過去には1対5の株式分割や自己株買い、増配など)を継続実施してきた経緯があり、株主還元への姿勢は強く、これが株価の下値を支えています(UNVERIFIED:直近FY3/2026での新規の自社株買い・増配の有無は本検証では未確認)。""",
"en": """**Company overview:** Idemitsu Kosan (5019) is Japan #2 oil refiner and distributor — about 30% domestic gasoline-station share, with refineries in Hokkaido, Chiba, Aichi, and Tokuyama. Plus a High-Functional Materials segment — organic-EL blue emitter materials (for smartphone / TV displays), lithium-ion battery materials, overseas lubricant sales — gives Idemitsu a unique diversification axis. Simply put: a comprehensive energy company anchored in refining while growing high-tech material businesses.

**How did business move?** FY3/2026 Q3 cumulative (Apr-Dec): revenue ¥5.9446T (-13.6%), operating profit ¥36.7B (-70.2%), recurring profit ¥54.9B (-66.8%), net profit attributable to parent shareholders ¥52.578B (-58.75%) — both revenue and profit fell sharply. The main cause is the fuel oil segment deterioration; the High-Functional Materials segment held strong. Full-year guidance is unchanged, with a continued severe business environment expected. The prior year (FY3/2025) achieved operating profit +30.84% via cost discipline, but this year is the reaction, with profit sharply down.

**Why did business move this way?** The biggest factor is the major decline in the fuel oil segment. Idemitsu profit partially depends on inventory valuation time-lag effects (crude-price changes affecting profit with a time lag), so earnings swing with crude oil prices. This year, crude prices entered a downward phase, shrinking inventory valuation gains on held crude — combined with cost increases from major periodic maintenance — sharply squeezed fuel oil segment profit. Meanwhile, the High-Functional Materials segment (organic-EL blue emitters, lithium-battery materials, etc.) stayed strong, and overseas lubricant sales also grew. But the High-Functional Materials segment is still small in scale and has not been enough to offset the fuel oil drop.

**Why did the stock move this way?** Three main reasons. 1. The market has priced in earnings deterioration — A -70.2% operating profit drop is downward pressure on the stock. 2. Caution about crude-price-dependent structural fragility — The structural fragility of inventory valuation effects swinging profit is being recognized by the market. 3. ESG investor screens — Institutional investors limiting fossil-fuel exposure (especially European ESG funds) will not add even with earnings improvement, capping upside. On the other hand, Idemitsu has historically continued PBR-improvement measures (a past 1-for-5 stock split, buybacks, dividend hikes). The strong shareholder-return stance supports the floor (UNVERIFIED: whether a new buyback or dividend hike was announced specifically within FY3/2026 is not confirmed in this verification)."""}

PET["5020"] = {"jp": """**会社概要:** ENEOSホールディングス(5020)は日本最大の石油精製・販売会社 — 国内のガソリンスタンドのシェア約50%を持ち、製油所の稼働率の高さで業界をリードしています。 旧JXTGエネルギーから商号変更した会社で、子会社にENEOS(石油精製・販売)、JX金属(銅・電子材料の生産・販売)、JX石油開発(海外油田の開発)を持つ総合エネルギー企業。 簡単に言えば、『日本最大の石油会社+銅・電子材料事業+海外油田開発を持つエネルギー企業のリーダー』。

**業績の動き:** 2026年3月期の通期業績は、営業利益¥4,666億円(在庫影響を除くと¥4,744億円)、親会社株主に帰属する当期純利益¥2,587億円(+14.4%)で着地し、当初予想の¥1,350億円を91%も上回る大幅な上振れとなりました。 配当は年間¥34(中間¥17+期末¥17)で安定維持、来期(2027年3月期)も¥34と継続予定。 加えて、自己株買いを上限8,200万株または¥500億円で実施することを決定。

**なぜ業績がこう動いたのか:** 会社が決算で開示した『利益急増の最大要因』は、石油精製・販売事業の収益性が想定より大幅に改善したことです。 原油価格と石油製品の販売価格の差(マージン)が業界全体で改善傾向にあり、ENEOSは国内最大の精製事業者としてこの恩恵を最も大きく受けました。 加えて、業界再編による寡占化の進行で、価格決定力が強化されています(UNVERIFIED:本検証では具体的な東亜石油の完全子会社化・富士石油TOBの最新ステータスを直接確認できず)。 子会社のJX石油開発(海外油田からの収益)とJX金属(銅+電子材料のEV関連需要)も利益に貢献しており、石油精製事業以外の収益基盤も育っています。 要するに、『主力の石油精製事業の利益率が大きく改善し、子会社の事業も補完的に貢献して、想定を91%も上回る業績を達成した』というのが今期の好決算のストーリーです。

**なぜ株価がこう動いたのか:** 株価が動いた主な理由は3つ。 1つ目は業績の大幅上振れと安定配当の維持 — 当初予想を91%も上回る業績達成+安定配当維持の発表が、機関投資家の買いを引き起こしました。 2つ目は来期(2027年3月期)の業績見通しの強さ — 売上+9.2%(¥12.85兆円)、営業利益+30.7%(¥6,100億円)、純利益+60.4%(¥4,150億円)というFY27予想が業績モメンタムへの信頼を高めています。 3つ目は自己株買いと株主還元強化 — 上限¥500億円の自己株買い決定は、PBR改善+EPS引き上げを通じて株価評価を高めると市場が判断。 配当利回り(予想ベースで2.7%前後)+PBR1倍前後の水準が、インカム志向の長期投資家を引きつけています(UNVERIFIED:『過去6か月で日経平均を+8.7%アウトパフォーム』との具体数値は本検証では確認できず)。""",
"en": """**Company overview:** ENEOS Holdings (5020) is Japan largest oil refiner and distributor — with about 50% market share of domestic gasoline stations, leading the industry in refinery utilization. Renamed from JXTG Energy, it is a comprehensive energy company with subsidiaries including ENEOS (oil refining / distribution), JX Metals (copper + electronic materials production / sales), and JX Oil & Gas Exploration (overseas oil-field development). Simply put: the leader of Japan largest oil company + copper / electronic materials business + overseas oil-field development.

**How did business move?** FY3/2026 full-year results: operating profit ¥466.6B (¥474.4B excluding inventory impact), and net profit attributable to parent shareholders ¥258.7B (+14.4%) — beating the initial guidance of ¥135B by 91%, a major upside surprise. Dividend held stable at ¥34 annually (¥17 interim + ¥17 year-end); FY3/2027 also plans ¥34. In addition, a buyback decision was made with an upper limit of 82M shares or ¥50B.

**Why did business move this way?** The company disclosed that the biggest factor in the profit surge was that the oil refining / distribution segment profitability improved much more than expected. The margin (spread between crude oil price and refined product selling price) improved across the industry, and ENEOS, as the country largest refiner, benefited the most. In addition, industry consolidation is increasing oligopoly concentration and strengthening pricing power (UNVERIFIED: specific current status of Toa Oil full subsidiarization / Fuji Oil TOB was not directly confirmed in this verification). Subsidiaries JX Oil & Gas Exploration (income from overseas oil fields) and JX Metals (copper + electronic materials for EV-related demand) also contributed to profit, building earnings sources beyond oil refining. In short: the core refining business profit margin improved substantially, with subsidiaries also complementarily contributing, delivering earnings 91% above the original guidance.

**Why did the stock move this way?** Three main reasons. 1. Major guidance beat + stable dividend maintenance — Achieving 91% above the original guidance + stable dividend maintenance triggered institutional buying. 2. Strong FY3/2027 (next year) outlook — Revenue +9.2% (¥12.85T), operating profit +30.7% (¥610B), net profit +60.4% (¥415B) FY27 guidance is building trust in earnings momentum. 3. Buyback + shareholder-return strengthening — The ¥50B-cap buyback decision is judged by the market as raising stock valuation through PBR improvement + EPS lift. The forecast dividend yield (around 2.7%) + PBR around 1.0x attract income-mandate long-horizon investors (UNVERIFIED: the specific claim of +8.7% outperformance vs Nikkei over the past 6 months could not be corroborated in this verification)."""}

PET["5011"] = {"jp": """**会社概要:** ニチレキグループ(5011)は東京都千代田区本社・1943年創業の日本最大手のアスファルト応用加工製品メーカー — 旧『日本瀝青化学工業所』として始まり、現在は『アスファルト応用加工製品事業』(アスファルト乳剤、改質アスファルト、防水材、舗装材料の製造)+『道路舗装事業』(舗装工事の施工)を2本柱として、国内の道路インフラ整備を支える企業。 2024年10月1日に持株会社体制へ移行し『ニチレキグループ』に商号変更しました。 主要顧客は国土交通省+地方自治体+高速道路会社(NEXCO東日本・中日本・西日本)+建設会社で、長年の取引関係を築いてきました。 簡単に言えば、『日本の道路インフラの縁の下の力持ちとして、アスファルトを作って道路を舗装する会社』。

**業績の動き:** 2026年3月期の実績は、売上高¥758.53億円(微増)、経常利益¥60.7億円(-13.8%)。 売上は伸びましたが、利益面は減益となりました。 配当は前期比¥5増配の¥80(中間¥40+期末¥40)。 2027年3月期は売上¥800億円(+5.6%)、営業利益¥70億円(+11.7%)、経常利益¥73億円(+3.6%)への回復見通しを発表しており、減益局面は一時的との見方が経営側から示されています。

**なぜ業績がこう動いたのか:** 会社が決算で開示した『減益要因』は明確で、主に2つあります。 1つ目はアスファルト応用加工製品事業セグメントの利益減少 — このセグメントの利益が落ちたことが、全体の業績悪化の主因です。 アスファルトの原料は石油由来のため、原油価格の高水準維持+為替の円安進行で、アスファルト原料の調達コストが構造的に上昇しました。 会社は『製品価格の見直し+原価管理に努めた』と説明していますが、コスト上昇への完全な価格転嫁が遅れる構造で、マージンが圧縮されています。 2つ目は道路舗装事業セグメントは増益 — 一方で、道路舗装事業は増益となりました。 国土強靱化計画+老朽道路の更新需要+災害復旧需要が継続しているため、施工需要は底堅く、量的成長を続けています。 つまり、『材料製造は原料高で利益を落とし、施工事業は需要堅調で利益を伸ばしたが、材料の落ち込みの方が大きく全体は減益』というのが今期の業績ストーリーです。

**なぜ株価がこう動いたのか:** 株価が動いた主な理由は3つ。 1つ目は配当の継続的な増額(¥75→¥80) — 業績が減益でも配当を増額する方針は、機関投資家からの株主還元評価を高めており、株価の下値を支えています。 2つ目は来期(2027年3月期)の業績回復見通し — 売上+5.6%、営業利益+11.7%、経常利益+3.6%という回復ガイダンスが示されており、減益は一時的との見方が市場に浸透しています。 3つ目は『国土強靱化』テーマでの注目 — アスファルト・道路舗装は『公共投資・国土強靱化』テーマで景気循環に左右されにくい安定需要があるため、長期保有株として機関投資家から安定需要を集めています。""",
"en": """**Company overview:** Nichireki Group (5011) is Japan largest asphalt-applied processing-product maker headquartered in Tokyo-Chiyoda, founded 1943 as Nippon Bituminous Chemical Industries. Today it operates two pillars: Asphalt-applied processing products (production of asphalt emulsions, modified asphalt, waterproofing, paving materials) + Road paving (paving construction work) — supporting Japan road infrastructure. The company shifted to a holding-company structure on October 1, 2024 and was renamed Nichireki Group Inc. Main customers: MLIT + local governments + expressway operators (NEXCO East / Central / West) + construction firms. Simply put: a company that, as the unsung backbone of Japan road infrastructure, manufactures asphalt and paves roads.

**How did business move?** FY3/2026 actuals: revenue ¥75.853B (slight increase), recurring profit ¥6.07B (-13.8%). Revenue grew but profit fell. Dividend raised ¥5 YoY to ¥80 (¥40 interim + ¥40 year-end). FY3/2027 guidance: revenue ¥80B (+5.6%), operating profit ¥7B (+11.7%), recurring profit ¥7.3B (+3.6%) — a recovery, with management signaling the down-cycle is temporary.

**Why did business move this way?** The company disclosed two main profit-decline drivers. 1. Asphalt-applied processing-products segment profit declined — this segment profit drop is the main driver of overall earnings deterioration. Asphalt feedstock is petroleum-derived, so sustained-high crude prices + yen weakness structurally lifted feedstock procurement costs. The company stated it worked on product-price reviews + cost management, but full pass-through to selling prices lagged, compressing margins. 2. Road paving segment profit grew — meanwhile, road paving saw a profit increase. National-resilience plan + aging-road replacement + disaster-recovery demand continue, so paving demand is firm and volume keeps growing. In short: Materials manufacturing lost profit due to high feedstock costs, while paving gained profit on strong demand — but the materials decline outweighed paving gains, so overall it was a profit decline.

**Why did the stock move this way?** Three main reasons. 1. Continued dividend increase (¥75 to ¥80) — Raising the dividend even with a profit decline raises institutional view of shareholder return and supports the floor. 2. FY27 earnings recovery guidance — Revenue +5.6%, operating profit +11.7%, recurring profit +3.6% recovery guidance is being absorbed by the market as the decline is temporary. 3. Attention as a national-resilience theme stock — Asphalt / road paving has stable demand insulated from economic cycles under public investment / national resilience themes, attracting steady demand from long-horizon institutional investors."""}

# === Marine ===
MAR["9171"] = {"jp": """**会社概要:** 栗林商船(9171)は、東京都千代田区大手町本社・1894年(明治27年)創業/1919年(大正8年)設立の内航海運(=日本国内の港同士を結ぶ海上輸送)の老舗です。 主力は内航大型RoRo船(Roll-on/Roll-off=トラックや車両を自走で船内に積み込む方式の輸送船)で、北海道(苫小牧・釧路)-仙台-東京-清水-名古屋-大阪を結ぶ航路を運営しています。 中核貨物は伝統的に新聞用紙等の紙関連で、主要顧客には王子物流が挙げられます。 加えて、シャーシ貨物(鋼材・建材)、商品車両(自動車)、雑貨など多様な貨物を取り扱い、北海道-本州間の物流を支えています。 連結セグメントは海運業に加えて、北海道のホテル事業(登別グランドホテル等)と不動産事業(室蘭中心)を有しています。 一言で言えば、『北海道-本州間の大型RoRo輸送を中核とする内航海運の老舗+北海道のホテル・不動産事業を持つ複合企業』。

**業績の動き:** 2026年3月期通期予想(上方修正後)は、売上高¥537億円(+1%)、営業利益¥25億円(-7%)、経常利益¥28億円、純利益¥37億円(+88%)。 純利益の大幅増益は、2025年10-12月期に政策保有株3銘柄を売却して特別利益¥19億円を計上した一過性要因によるものです。

**なぜ業績がこう動いたのか:** 業績の構造を分解すると3つあります。 1つ目は売上が微増を維持できた理由=モーダルシフトと安定した北海道-本州物流需要 — 2024年問題(トラックドライバーの労働時間規制)を背景に『トラック輸送から船舶輸送への切り替え(モーダルシフト)』が政府主導で推進されており、内航RoRoの貨物需要は底堅く推移しました。 2つ目は営業利益が-7%に落ちた理由=燃料費高止まり+船員人件費上昇+運賃改定の遅れ — 重油価格の高止まり、業界全体の船員確保難による賃金引き上げが構造的にコストを押し上げる一方、内航運賃の改定は荷主との交渉が必要で時間がかかり、コスト転嫁が間に合いませんでした。 3つ目は純利益+88%は特別利益の一過性要因 — 2025年10-12月期に政策保有株3銘柄を売却し、特別利益¥19億円を計上(UNVERIFIED:売却銘柄として三井住友FG・東京海上HD等が含まれるかは本検証では確認できず)。 これにより通期純利益が¥37億円(+88%)へ上方修正されました。

**なぜ株価がこう動いたのか:** 上方修正発表日(2025年9月22日)にストップ高¥1,440(+¥300、+26%)を記録。 株価が動いた主な理由は3つ。 1つ目は政策保有株売却=資本効率改善への期待 — 東証のPBR改善要請を背景に、政策保有株(=取引先などとの関係維持のために保有している他社株式)を整理することは、機関投資家から『資本コスト意識が高い経営』として評価されやすく、残存する政策保有株の追加売却+株主還元強化への期待が高まりました。 2つ目は北海道-本州間内航RoRoの安定的なポジション=事業基盤の再評価 — 内航RoRoは専用港湾設備+船舶+運航ノウハウが必要で新規参入が難しく、栗林商船の北海道-本州間ネットワークが、コスト圧迫局面でも『中長期では運賃改定で取り戻せる』との評価に繋がりました。 3つ目はモーダルシフト政策の構造的追い風 — 国土交通省の物流効率化政策(トラック→鉄道・船舶への転換)は、内航海運業界にとって構造的な追い風で、栗林商船の中期成長ストーリーが見直されています。""",
"en": """**Company overview:** Kuribayashi Shosen (9171) is a Tokyo (Chiyoda-Otemachi) headquartered coastal-shipping company — founded 1894 (Meiji 27) and incorporated 1919 (Taisho 8). The core business is coastal large RoRo (Roll-on/Roll-off, vehicles drive themselves onto the ship) cargo shipping, operating routes connecting Hokkaido (Tomakomai / Kushiro) - Sendai - Tokyo - Shimizu - Nagoya - Osaka. The traditional core cargo has been newspaper paper and other paper-related products, with Oji Logistics named as a main customer. Beyond that, the company carries chassis cargo (steel, building materials), commercial vehicles (autos), and miscellaneous freight, supporting Hokkaido-Honshu logistics. Consolidated segments include shipping plus hotel operations in Hokkaido (Noboribetsu Grand Hotel etc.) and real estate operations (centered on Muroran). In short: a long-established coastal-shipping group whose core is large RoRo between Hokkaido and Honshu, with additional Hokkaido hotel and real-estate businesses.

**How did business move?** FY3/2026 full-year forecast (post-upward-revision): Revenue ¥53.7B (+1%), OP ¥2.5B (-7%), recurring ¥2.8B, NP ¥3.7B (+88%). The NP surge came from selling 3 policy-held stocks in Oct-Dec 2025 and booking a ¥1.9B special gain, a one-off.

**Why did business move this way?** The earnings structure decomposes into 3 reasons. 1. Revenue +1% sustained = modal shift + stable Hokkaido-Honshu logistics demand — The 2024 Problem (driver labor-hour rules) is government-driving modal shift from truck to ship, supporting firm coastal RoRo cargo demand. 2. OP -7% due to fuel + labor + delayed rate revisions — Sustained heavy-fuel-oil prices + industry-wide seafarer shortage driving wage hikes structurally lifted costs, while coastal rate revisions require negotiation with shippers and lag the cost increase. 3. NP +88% is a one-off from special gain — In Oct-Dec 2025, Kuribayashi sold 3 policy-held stocks and booked a ¥1.9B special gain (UNVERIFIED: whether SMFG / Tokio Marine HD were specifically among the three issuers sold could not be independently confirmed in this verification), upward-revising full-year NP to ¥3.7B (+88%).

**Why did the stock move this way?** Stock hit limit-up at ¥1,440 (+¥300, +26%) on the upward-revision announcement day (2025-09-22). Three main reasons. 1. Policy-stock sale = expectation of capital-efficiency improvement — TSE PBR-improvement push makes rationalizing policy holdings (equity stakes held purely for business-relationship maintenance) well-rated by institutions as capital-cost-conscious management. Expectations rose for further policy-stock sales + stronger shareholder returns. 2. Stable Hokkaido-Honshu coastal RoRo position re-rated — Coastal RoRo requires specialized port facilities + vessels + operating know-how, making new entry difficult. Kuribayashi Hokkaido-Honshu network supports the view that mid-term rate revisions will recover today cost pressure. 3. Modal-shift policy structural tailwind — MLIT logistics-efficiency policy (truck to rail / ship) is a structural tailwind for coastal shipping, prompting investors to re-rate Kuribayashi mid-term growth story."""}

# === LT ===
LT["9075"] = {"jp": """**会社概要:** 福山通運(9075)は、広島県福山市本社の老舗LTL(Less-than-Truckload、混載貨物)輸送大手。 1948年創業で、関東・中部・関西・中四国・九州を結ぶ全国ネットワークを持つ『フクツー(福山通運)』ブランドの宅配・特積み輸送業者。 単純な国内貨物輸送だけでなく、チャーター輸送+流通加工(倉庫・流通センター業務)+国際物流(海上・航空フォワーディング、東南アジア+中国向け輸送)+不動産賃貸 を組み合わせた総合物流企業として展開しています。 一言で言えば、『広島から全国を結ぶ西日本発の特積み大手、フクツー』のような存在。

**業績の動き:** 2026年3月期は売上¥3,185.82億円(+5.3%)、営業利益¥93.47億円(+26.9%)、経常利益¥114.75億円(+15.7%)、純利益¥136.96億円(+56.6%)で全セグメント増収増益。 セグメント内訳は運送事業¥2,445.73億円(+4.3%、OP +31.3%)、貸切事業¥278.07億円(+5.9%、OP +16.8%)、流通加工事業¥237億円(+6.0%、OP +16.0%)、国際事業¥152.44億円(+28.5%、OP +55.4%)。 配当は前期¥70から¥76への増配。

**なぜ業績がこう動いたのか:** 業績が大幅増益となった理由は3つ。 1つ目は2024年問題対応の運賃値上げが奏功 — ヤマト・佐川・セイノーと並んで、福山通運も荷主への運賃改定交渉を積極的に進め、運送事業のセグメントOP +31.3%という強い伸びは運賃改定効果の本格化を示すものです。 2つ目は国際物流事業の急成長 — セグメント売上+28.5%、OP +55.4%という急加速は、東南アジア+中国向け物流需要の拡大、フォワーディング案件の獲得が組み合わさった結果。 3つ目は流通加工事業+貸切事業の両方で2桁の営業利益成長 — 流通加工事業OP +16.0%、貸切事業OP +16.8%と、運賃改定+業務効率化+料金適正化の効果が複数セグメントに波及。 純利益+56.6%は営業段階での増益(+26.9%)に加え、経常段階以下の項目で押し上げ効果があったとみられますが、特別利益の具体的な内訳は公開資料からはUNVERIFIED。

**なぜ株価がこう動いたのか:** 株価は上昇トレンド。 動いた主な理由は3つ。 1つ目は全項目で大幅増益+全セグメントで増収増益という強い決算 — LTL業界の構造的改善(2024年問題対応の運賃値上げ)の中心的受益銘柄として注目度が高まっています。 配当も¥70→¥76→FY27予想¥100へと段階的な増額が計画されています(ただし配当利回りは約1.5%水準でインカム妙味は限定的)。 2つ目は広島・中四国を本拠地とする地理的優位+国際物流の長期成長余地 — 西日本最大の物流拠点である広島市・福山市を中心としたネットワークは関西-九州の物流動線の中継地として価値が高く、東南アジア+中国向けの国際物流は構造的に成長分野で、中長期的に業績の柱の一つに成長する可能性があります。 3つ目はLTL業界の運賃改定効果持続+EC物流市場への対応進捗 — 2024年問題対応の運賃改定は業界全体の収益体質を構造的に改善する効果を持ち、EC市場の成長を取り込める構造に変化しています。""",
"en": """**Company overview:** Fukuyama Transport (9075) is an established LTL (less-than-truckload, mixed-cargo) trucker headquartered in Fukuyama, Hiroshima. Founded 1948 — the Fukutsu brand parcel / LTL operator spans Kanto / Chubu / Kansai / Chu-Shikoku / Kyushu nationwide. Beyond pure domestic freight: charter (full-vehicle) + distribution-processing (warehouse / DC operations) + international logistics (ocean / air forwarding, SE Asia + China) + real-estate rental — a comprehensive logistics operator. Put simply: Fukutsu — Western Japan LTL major connecting Hiroshima to nationwide.

**How did business move?** FY3/2026: Revenue ¥318.58B (+5.3%), OP ¥9.347B (+26.9%), recurring ¥11.48B (+15.7%), NP ¥13.70B (+56.6%) — all segments grew. Segment detail: trucking ¥244.57B (+4.3%, OP +31.3%), charter ¥27.81B (+5.9%, OP +16.8%), distribution-processing ¥23.7B (+6.0%, OP +16.0%), international ¥15.24B (+28.5%, OP +55.4%). Dividend stepped up from ¥70 to ¥76 per share.

**Why did business move this way?** Three reasons for the sharp earnings gain. 1. 2024-Problem rate-revisions paid off — Alongside Yamato, Sagawa, and Seino, Fukuyama actively pushed shipper rate increases. Trucking segment OP +31.3% shows the rate-hike effect in force. 2. International-logistics segment surge — Revenue +28.5%, OP +55.4% combines SE Asia + China logistics demand growth and forwarding wins. 3. Double-digit OP growth in distribution-processing + charter — Distribution-processing OP +16.0%, charter OP +16.8%; rate revisions + operational efficiency + price normalization rippled across segments. NP +56.6% reflects operating-level gain (+26.9%) plus uplift in below-operating items; the specific composition of any special gains (policy-stock sales / real-estate gains) is UNVERIFIED from public disclosures.

**Why did the stock move this way?** Stock holds an uptrend. Three main reasons. 1. Strong earnings beat across all metrics — Recognized as a central LTL beneficiary of the industry structural improvement (2024-Problem rate cycle). Dividend trajectory ¥70 to ¥76 to FY27 guidance ¥100 supports step-up returns (though yield ~1.5% means income appeal is limited). 2. Hiroshima / Chu-Shikoku geographic advantage + international-logistics growth runway — Network centered on Hiroshima and Fukuyama is critical for Kansai-Kyushu transit. SE Asia + China international logistics is the structural growth area with high growth rates, potentially a major earnings pillar long-term. 3. Sustained LTL rate-hike effect + EC-logistics adoption progress — 2024-Problem revisions structurally improve industry economics. The company is positioned to capture EC growth."""}

LT["9085"] = {"jp": """**会社概要:** 北海道中央バス(9085)は、小樽市本店(本社機能は小樽・札幌に分散)・北海道最大手バス事業者。 札幌市内・小樽市・千歳市・苫小牧市などの道央エリアを中心に、路線バス+高速バス(札幌-旭川・札幌-函館・札幌-釧路)+貸切観光バス+空港リムジンバス(新千歳空港)を運営する『北海道のバス業界リーダー』。 加えて北海道内での建設事業(中央バス建設グループ)+不動産事業+物販事業(中央バス商事)を展開し、北海道経済への幅広い貢献を行っています。 一言で言えば、『北海道の道央エリアと新千歳空港の足を担う地域インフラ』のような存在。

**業績の動き:** 2026年3月期は売上¥383.84億円(+6.7%)、営業利益¥26.51億円(+17.1%)、経常利益¥29.87億円(+13.2%)、純利益¥27.81億円(+22.9%)で全項目大幅増収増益。 第3四半期累計の経常利益は前年同期比2.6倍に拡大という、北海道経済の活況を反映した強い決算となりました。 ただし、2027年3月期会社予想は売上¥377億円(-1.8%)、営業利益¥16億円(-39.6%)、経常利益¥19億円(-36.4%)、純利益¥12億円(-56.8%)と大幅減益見通しで、建設事業の反動減+原材料費・人件費上昇を理由として開示しています。

**なぜ業績がこう動いたのか:** 業績が急加速した理由は3つ。 1つ目は北海道へのインバウンド観光客の急回復 — 訪日外国人数が過去最高水準で推移し、北海道は『冬季スキー+夏季避暑+グルメ』のテーマで中国・韓国・台湾・東南アジア・オーストラリアからの観光客が急増。 ニセコ・ルスツ・トマムなどスキーリゾートへの輸送需要が大幅に拡大し、貸切バス+空港リムジンバスの収益が押し上げられました。 2つ目は新千歳空港リムジンバスの需要拡大+バス運賃改定の効果 — 国際線就航便の増加+国内線旅客数の回復で新千歳空港リムジンバス利用者数が増加。 加えて路線バス運賃の値上げで収益改善に寄与しました。 3つ目は建設事業セグメントの好調+コスト管理の徹底 — 道内のインフラ整備需要+ホテル・商業施設建設の増加で中央バス建設グループの売上+利益が大幅拡大。 ただしこの建設事業の好調は来期反動減のリスク要因として会社が認識しています。

**なぜ株価がこう動いたのか:** 株価は上昇トレンド。 動いた主な理由は3つ。 1つ目は経常利益2.6倍(Q3累計)+通期増収増益という業績モメンタム — 札証単独上場銘柄として流動性は限定的ですが、北海道インバウンドテーマで物色される機関投資家からの買いが入っています。 ただしFY27会社予想は大幅減益見通しのため、業績モメンタム継続には不確実性があります。 2つ目は北海道インバウンドの長期成長+新千歳空港の戦略的価値 — 中国・韓国・台湾・東南アジアからの観光需要が中長期的に拡大する見込みで、特に冬季スキー需要+夏季避暑需要の二季節構造が強み。 新千歳空港は北海道の主要国際空港で長期成長が見込まれます。 3つ目は道央エリアでのシェア+建設事業の北海道経済との連動+多角化ポートフォリオ — 道央の路線バス主要シェア、北海道新幹線延伸+再開発+ホテル建設等のインフラ投資による建設事業機会、バス+建設+不動産+物販の多角化が景気変動リスクを分散しています。 PBR0.6倍前後の低バリュエーションも下値支え要因です。""",
"en": """**Company overview:** Hokkaido Chuo Bus (9085) is Hokkaido largest bus operator with its registered head office in Otaru (administrative functions split between Otaru and Sapporo). Operates local routes + highway buses (Sapporo-Asahikawa, Sapporo-Hakodate, Sapporo-Kushiro) + charter sightseeing buses + airport limousine buses (New Chitose) centered on the Doo region (Sapporo, Otaru, Chitose, Tomakomai). Beyond bus: Hokkaido construction (Chuo Bus Construction Group) + real estate (line-side commercial) + retail (Chuo Bus Shoji) — broad contribution to Hokkaido economy. Put simply: regional infrastructure serving Hokkaido Doo region and New Chitose airport access.

**How did business move?** FY3/2026: Revenue ¥38.384B (+6.7%), OP ¥2.651B (+17.1%), recurring ¥2.987B (+13.2%), NP ¥2.781B (+22.9%) — meaningful growth across the board. Q3 YTD recurring profit grew 2.6x YoY — a strong result reflecting Hokkaido economic vitality. However, FY3/2027 company guidance is for sharp declines: Revenue ¥37.7B (-1.8%), OP ¥1.6B (-39.6%), recurring ¥1.9B (-36.4%), NP ¥1.2B (-56.8%) — driven by construction-segment normalization plus rising raw-material and labor costs as disclosed by management.

**Why did business move this way?** Three reasons for the acceleration. 1. Hokkaido inbound surge — Foreign visitor numbers at record highs; Hokkaido captures winter ski + summer cooling + gourmet themes from China, Korea, Taiwan, SE Asia, Australia. Niseko, Rusutsu, Tomamu ski resorts drove charter + airport-limousine revenue dramatically. 2. New Chitose airport limousine demand + bus fare-revision effect — More international routes + domestic passenger recovery lifted ridership. Plus MLIT-approved fare increases improved revenue. 3. Construction segment strength + cost discipline — Hokkaido infrastructure + hotel / commercial construction lifted Chuo Bus Construction Group. However, management flags this construction surge as a reaction-driven decline risk for next year.

**Why did the stock move this way?** Stock holds an uptrend. Three main reasons. 1. Recurring profit Q3 cumulative 2.6x + full-year growth + earnings momentum — Sapporo-Securities-Exchange-only listing limits liquidity, but Hokkaido-inbound-themed institutional money is buying. However, FY27 sharp-decline guidance creates uncertainty about momentum continuation. 2. Long-term Hokkaido inbound growth + New Chitose Airport strategic value — China / Korea / Taiwan / SE Asia tourism to Hokkaido is set to expand mid-long-term, with winter-ski + summer-cooling two-season structure as a strength. New Chitose, Hokkaido main international airport, keeps expanding routes. 3. Doo regional share + construction tied to Hokkaido economy + diversified portfolio — Strong Doo local-bus share, construction-segment opportunity from Hokkaido Shinkansen extension + redevelopment + hotels, plus bus + construction + real estate + retail mix diversifies cyclical risk. PBR around 0.6x also provides downside support."""}

def apply(sector_file, corrections):
    p = BASE / sector_file
    data = json.loads(p.read_text(encoding='utf-8'))
    applied = []
    for t, c in corrections.items():
        if t in data:
            data[t]['jp_summary'] = c['jp']
            data[t]['en_summary'] = c['en']
            applied.append(t)
    p.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding='utf-8')
    json.loads(p.read_text(encoding='utf-8'))  # validate
    return applied

print("Petroleum:", apply("company_research_petroleum_sector.json", PET))
print("Marine:   ", apply("company_research_marine_sector.json", MAR))
print("LT:       ", apply("company_research_land_transport_sector.json", LT))
print("All JSONs validated OK")
