# -*- coding: utf-8 -*-
"""Assemble the new 水産・農林業 (Fishery / Agriculture / Forestry) sector JSON file
from the 8 Sonnet agent outputs. Each entry has the full jp_summary + en_summary
prose (with bold-markdown section headers), 8 card-display fields, sources, notes,
plus tab (R+xS- / R+xS+) and bucket assignments."""
import json, sys
from pathlib import Path
sys.stdout.reconfigure(encoding='utf-8')

OUT = Path(r"c:\Users\Sahal Saeed\Documents\tempest_ai\quick\New_quick\new_quick\quite_change\data\company_research_agri_fishery_sector.json")

DATA = {
    "_meta": {
        "sector": "AgriFishery",
        "sector_code_topix33": "水産・農林業 (Fishery, Agriculture & Forestry)",
        "sector_name_en": "Fishery, Agriculture & Forestry",
        "sector_name_jp": "水産・農林業",
        "fiscal_year_target": "Mixed fiscal year-ends (March, May, June); latest available actuals or guidance used per company.",
        "data_vintage": "2026-06 (latest available reports)",
        "filter_default": "売上○",
        "description": "Fishery, Agriculture & Forestry sector (TOPIX-33). Mix of seafood majors (Nissui, Maruha Nichiro, Kyokuyo), seed companies (Sakata Seed, Kaneko Seeds), specialty domestic producers (Hokuto mushrooms, Axyz poultry), and organic farm-to-home (Akikawa Bokuen). All 8 covered companies are R+ in FY-latest.",
        "generated": "2026-06-07",
        "method": "Sonnet 4.6 + locked lighter prompt (bold-headers + explain-the-because + verification pass). One agent per ticker.",
        "format": "4-section bold-headered plain-language summary (会社概要 / 業績の動き / 業績が動いた理由 / 株価が動いた理由). Verification audit trail in notes.",
        "sector_statistics": {
            "total_listed_in_topix33_sector": 12,
            "considered_in_this_analysis": 8,
            "qualifying_as_R_plus": 8,
            "excluded": [],
            "smaller_unlisted_or_not_covered": "TOPIX-33 水産・農林業 has approximately 12 listed companies per Yahoo Finance Japan. The 4 not covered in this pass are smaller names (egg producers, niche forestry, etc.) — may be added in a follow-up pass."
        }
    },
    "1301": {
        "name": "Kyokuyo",
        "tab": "R+xS-",
        "bucket": "seafood_value_unrecognized",
        "rev_dir": "up", "rev_pct": "+10.5%",
        "op_dir": "down", "op_pct": "-3.1%",
        "net_dir": "up", "net_pct": "+1.5%",
        "stock_yoy_estimate": "High ¥5,450 (Feb 2026) → current ~¥4,285 (Jun 2026); approx -21% from 52-week high",
        "biz_classification": "水産大手 / Major seafood company",
        "jp_summary": "**会社概要:** 極洋（きょくよう）は1937年創業の水産大手で、東証プライムに上場。マグロ・サーモン・エビ・タラコ・カニなど幅広い水産物を世界中から調達・加工して日本国内に販売する「水産事業」が売上の約6割を占める。それに加えて、スーパー向けの生鮮魚介類を扱う「生鮮事業」、煮魚・焼魚などの冷凍食品やおつまみ類を作る「食品事業」、水産物の物流を担う「物流サービス事業」の4つの柱で成り立っている。マグロの養殖やサーモンの陸上養殖にも関わっており、安定調達を強みとする会社だ。\n\n**業績の動き:** 直近の2026年3月期（2025年4月〜2026年3月）の通期連結決算は、売上高が3,346億円（前期比＋10.5%）と大きく伸びた一方、営業利益は107億円（前期比▲3.1%）、経常利益は100億円（▲7.6%）と、売上は増えているのに利益が減るという「増収減益」の結果となった。純利益は68億円（＋1.5%）とほぼ横ばい。配当は前期の1株130円から150円に増配しており、株主還元は維持している。来期（2027年3月期）は売上3,650億円・営業利益120億円・純利益72億円と回復予想を出している。\n\n**業績が動いた理由:** 売上が10%以上伸びた主な理由は、サーモン・タラコ・カニなどの市場価格が世界的に上昇し、単価が高くなった分だけ金額が膨らんだためだ。ただし価格が上がると消費者が買い控えるため、サーモンやエビの販売「量」は減少した。冷凍食品事業では、原料の水産物が高騰したことで煮魚・焼魚などの定番商品が値上げを余儀なくされ、コンビニ向けを中心に販売数量が落ち込んだ。また、おつまみ・珍味はイカの原料高で値上げした結果、販売量がさらに減った。一方、水産物の調達・販売を担う水産事業や生鮮事業の売上自体は伸びており、減益の主犯は利益率の高い冷凍食品のコスト圧迫と、海外事業への先行投資費用だ。2026年2月には通期予想を下方修正（経常利益を125億円→103億円）しており、市場の期待を下回る着地となった。\n\n**株価が動いた理由:** 過去1年の株価は大きく上下している。2025年4月に年初来安値3,615円まで急落したのは、トランプ米大統領による大規模な相互関税発動（いわゆる「トランプショック」）で日本株全体が売られた影響を受けたためだ。そこから反発し、2026年2月27日には52週高値の5,450円まで上昇した。この上昇の背景には、①前期（2025年3月期）の好決算（営業利益＋25.8%増益）の評価、②2025年に三重県で世界最大級の陸上養殖場からのアトランティックサーモン出荷が始まり「サーモン養殖テーマ株」として買われたこと（2024年10月に日経が報道し水産株の中で独歩高となる場面もあった）がある。しかしその後、2026年2月の下方修正発表と、3月以降の関税懸念再燃・国内市況悪化観測を受けて4,000円台前半に押し戻されており、足元（2026年6月5日時点）は4,285円で取引されている。PERは約7倍と市場平均より低く、バリュー水準だが、利益回復が確認できるまでは様子見ムードが続いている。",
        "en_summary": "**Company overview:** Kyokuyo (founded 1937, TSE Prime) is one of Japan's major seafood companies. Its core business — accounting for roughly 60% of sales — involves sourcing, processing, and distributing a wide range of seafood (tuna, salmon, shrimp, cod roe, crab, etc.) from global markets to Japanese buyers. Three other segments round out the business: a Fresh Food segment selling chilled fish at supermarkets, a Food Products segment making frozen prepared dishes (simmered fish, grilled fish, seafood snacks), and a Logistics Services segment handling cold-chain distribution. The company also participates in tuna aquaculture and land-based salmon farming to secure stable supply.\n\n**How did business move?** The most recent completed fiscal year, FY2026 (April 2025 – March 2026), showed revenue of ¥334.6 billion (+10.5% year-on-year — a healthy jump), but operating profit fell to ¥10.7 billion (-3.1%) and ordinary profit dropped to ¥10.0 billion (-7.6%). Net profit was ¥6.84 billion (+1.5%), roughly flat. In other words, the company sold more but earned less per yen of sales. The dividend rose from ¥130 to ¥150 per share — a positive signal. For FY2027, management is guiding for revenue of ¥365 billion and operating profit of ¥12.0 billion, implying a meaningful recovery.\n\n**Why did business move this way?** Revenue grew because seafood market prices surged globally — salmon, crab, and cod roe all became more expensive, inflating the top line. But higher prices caused consumers to buy less by volume, so salmon and shrimp unit sales fell. In the frozen food segment, rising raw material costs forced Kyokuyo to raise prices on everyday items like simmered and grilled fish — and convenience-store buyers cut orders in response. The company had set itself ambitious profit targets at the start of FY2026 and was forced to cut those targets in February 2026 (ordinary profit guidance slashed from ¥12.5B to ¥10.3B).\n\n**Why did the stock move this way?** Over the past year the stock has swung sharply. It hit a low of around ¥3,615 in April 2025 because the Trump administration's reciprocal tariff announcement triggered a broad selloff across Japanese equities. From there it rebounded strongly, reaching a 52-week high of ¥5,450 on February 27, 2026, driven by FY2025's strong results and a Nikkei article in October 2024 spotlighting large-scale shipments from what is billed as the world's largest land-based Atlantic salmon farm in Mie Prefecture. After that peak, the February 2026 earnings downgrade and renewed tariff concerns pushed the stock back to the low ¥4,000s. As of June 5, 2026 it trades around ¥4,285 — a P/E of roughly 7x, well below market.",
        "sources": ["https://finance.yahoo.co.jp/quote/1301.T/financials","https://www.minato-yamaguchi.co.jp/minato/e-minato/articles/162141","https://kabuyoho.ifis.co.jp/index.php?action=tp1&bcode=1301&sa=report_tpx","https://jp.investing.com/news/stock-market-news/article-903984","https://www.kyokuyo.co.jp/files/20260501.pdf","https://www.nikkei.com/article/DGXZRST0527870R00C25A8000000/","https://stockanalysis.com/quote/tyo/1301/"],
        "notes": "Revenue ¥334.6B / OP ¥10.7B / NP ¥6.84B confirmed Yahoo Finance JP + Minato Shimbun. Dividend ¥150 confirmed multiple sources. Stock 52-week high ¥5,450 (Feb 27 2026), low ¥4,165 (Jun 4 2026); current ¥4,285 (Jun 5 2026, Matsui Securities). Salmon land-aquaculture catalyst confirmed (Itochu + Soul of Japan partnership in Mie, 10,000t/year). Feb 2026 downward revision confirmed by Nissyoku flash. April 2025 low attributed to broad market tariff shock — sector-logic, not company-specific source."
    },
    "1332": {
        "name": "Nissui",
        "tab": "R+xS+",
        "bucket": "seafood_majors_aqua_pricing",
        "rev_dir": "up", "rev_pct": "+5.1%",
        "op_dir": "up", "op_pct": "+27.2%",
        "net_dir": "up", "net_pct": "+8.4%",
        "stock_yoy_estimate": "+~55% over past year (52wk low ¥830 → current ~¥1,257; high ¥1,570)",
        "biz_classification": "水産・食品 / Seafood & Food Processing",
        "jp_summary": "**会社概要:** ニッスイ（旧社名：日本水産）は1911年創業の東証プライム上場企業で、事業の核は「海をまるごとビジネスにする」こと。4つのセグメントに分かれている。①水産事業：国内外での漁業・養殖・加工・商事。国内ではブリ・サバ・アジなど近海魚の養殖、チリなどの南米でサーモン類の養殖を展開。②食品事業：国内のチルド食品（コンビニ向け弁当・惣菜等）や冷凍食品の製造販売、および米国の有名シーフードブランド「Gorton's」を含む北米水産加工。③ファイン事業：EPA・DHAなど魚由来の機能性原料を医薬品・サプリ向けに製造販売。④物流事業：冷蔵倉庫・低温配送。26か国に事業拠点を持つグローバル水産企業。\n\n**業績の動き:** 最新の本決算は2026年3月期（FY2026）。売上高9,312億円（前期比＋5.1%、前期は8,861億円）——これは「年間で約450億円多く売れた」規模。営業利益404億円（前期比＋27.2%、前期は318億円）——1年で86億円増え、初めて400億円の壁を突破した過去最高益。純利益275億円（前期比＋8.4%、前期は254億円）。1株配当は32円（前期28円から4円増配）——2年連続の大幅増配。さらに60億円の自社株買いを実施し、株主還元は利益の57%超に達した。FY2027（2027年3月期）の会社計画では売上高9,800億円（＋5%）・営業利益425億円（＋5%）と再び最高益更新を狙う。\n\n**業績が動いた理由:** ①国内養殖の収益急回復——以前は赤字気味だった養殖部門が、ブリ・サバ等の販売価格上昇と生存率改善によるコスト低下が重なって急反転。価格と量の両方が改善したため、利益率が大きく跳ね上がった。②南米養殖の拡大——チリでのサーモン養殖が稼働軌道に乗り、漁獲量・出荷量が増加。さらに2026年1月にはチリの養殖企業「PESQUERA YADRAN」を完全子会社化し、アトランティックサーモンを新たに品種に加えた。③北米水産加工（主にGorton's）の改善——すりみなど原料価格の上昇を価格転嫁できたうえ、フィレ製品の生産能力拡大で工場稼働率が上がり、以前は足を引っ張っていた北米加工部門の赤字を一定程度解消した。④国内チルド食品の好調継続——コンビニ・スーパー向けの惣菜類が安定的に伸び続けており、食品事業全体を下支えした。\n\n**株価が動いた理由:** 過去1年（2025年6月頃〜2026年6月）の52週レンジは830〜1,570円程度で、概ね大幅上昇の流れだった。①2025年4月に一時795円まで急落——トランプ政権による「相互関税」発表を受けて日本株全体が暴落した巻き添えを食った。②その後V字回復し2025年11月に年初来高値1,258円——養殖事業の大幅増益を示す四半期決算が相次いで市場に好感された。水産事業の営業利益が前年比2倍超のペースで推移し、業績の上方修正が繰り返されたことで「業績が確実に変わった」との評価がついた。③2025年11月下旬にM&A発表で一時5.7%急落——チリの養殖企業買収を公表した翌営業日に投資家が売りで反応した。買収コストや統合リスクへの懸念から短期的に嫌気された。④2026年に入り再上昇——Q3の大幅増益を受けた上方修正と、大手証券が目標株価を1,950円に引き上げるなどアナリストの強気姿勢が維持され、FY2026本決算でも過去最高益を更新して株価は1,200〜1,570円帯で推移した。",
        "en_summary": "**Company overview:** Nissui (formerly Nippon Suisan, founded 1911, TSE Prime) is Japan's leading integrated seafood company — it fishes, farms, processes, and sells marine products across 26 countries. Four segments: Marine Products (fishing + aquaculture in Japan and Chile), Food Products (domestic ready-meals + the US Gorton's brand), Fine Business (pharmaceutical-grade EPA/DHA from fish), and Logistics. Think of it as turning the entire ocean into a supply chain.\n\n**How did business move?** FY2026 (year ended March 2026): Revenue ¥931.3 billion (+5.1% YoY), Operating profit ¥40.4 billion (+27.2% — first time ever above ¥40 billion, a record), Net profit ¥27.5 billion (+8.4%). Dividend raised to ¥32/share from ¥28 — the fifth consecutive annual increase. Buyback of ¥6 billion; total shareholder returns reached 57% of profit. For FY2027 the company guides ¥980B revenue (+5%) and ¥42.5B operating profit (+5%), another record target.\n\n**Why did business move this way?** (1) Domestic aquaculture turned around dramatically because yellowtail and mackerel prices rose while improved farming survival rates cut costs — a previously loss-making business flipped to a major profit engine. (2) South American salmon scaled up; Chilean output grew, and Nissui completed a full buyout of PESQUERA YADRAN in January 2026, adding Atlantic salmon to its existing trout and coho lineup. (3) North American processing recovered as surimi and fillet prices rose, lifting Gorton's-related factory utilization. (4) Domestic chilled foods stayed robust on continued convenience-store demand.\n\n**Why did the stock move this way?** 52-week range ~¥830–¥1,570. (1) Sharp drop to ¥795 in April 2025 — Trump tariff panic swept up Japanese equities. (2) Recovery to a then-record ¥1,258 by November 2025 — quarterly results confirmed the aquaculture turnaround. (3) Sudden 5.7% drop in late November 2025 — Chilean acquisition announcement spooked short-term holders on integration risk. (4) Re-ascent into 2026 — Q3 results showed operating profit +26.5% YoY, the company raised guidance again, dividend went to ¥32, and a major brokerage raised its target price to ¥1,950.",
        "sources": ["https://stockanalysis.com/quote/tyo/1332/financials/","https://irbank.net/E00014/pl","https://diamond.jp/zai/articles/-/1067836","https://finance.biggo.jp/news/jpx_tdnet_140120260513530461","https://www.zaikei.co.jp/article/20260525/854566.html","https://kabuyoho.ifis.co.jp/index.php?action=tp1&sa=report_pbr&bcode=1332","https://www.nikkei.com/article/DGXZQOUB142PV0U6A510C2000000/"],
        "notes": "FY2026 revenue ¥931.3B + OP ¥40.4B confirmed across stockanalysis.com, irbank.net, and diamond.jp/zaikei. Net profit ¥27.5B confirmed both sources. Dividend ¥32 confirmed. 52wk range ¥830.5–¥1,570 confirmed across investing.com and biggo TDnet flash. YADRAN acquisition price not disclosed publicly. YoY stock estimate approximate."
    },
    "1333": {
        "name": "Maruha Nichiro (→ Umios 2026)",
        "tab": "R+xS+",
        "bucket": "seafood_majors_aqua_pricing",
        "rev_dir": "up", "rev_pct": "+4.7%",
        "op_dir": "up", "op_pct": "+14.5%",
        "net_dir": "up", "net_pct": "+11.6%",
        "stock_yoy_estimate": "+22–24% YoY (Sep 2025 reference, pre-split basis)",
        "biz_classification": "水産・食品総合 / Seafood & Food Conglomerate",
        "jp_summary": "**会社概要:** マルハニチロは日本最大の水産・食品総合企業で、漁業・養殖から始まり、水産物の仕入れ・売買、冷凍食品・缶詰・ちくわ・フィッシュソーセージなどの加工食品製造、ペットフード製造（タイ工場から主に北米向け）、ファインケミカル（魚由来の医薬品原料）まで幅広く手がける。「水産会社」と思われがちだが、実際の利益の稼ぎ頭は食材流通・加工食品・海外事業であり、単なる漁業会社ではない。2026年3月に社名を「Umios（ウミオス）」に変更し、海を軸にした食のソリューション企業へのシフトを打ち出している。東証プライム上場。\n\n**業績の動き:** 直近本決算は2025年3月期の連結実績。売上高は1兆786億円（前期比＋4.7%）で初めて1兆円台を本格安定化させた。営業利益は303億円（同＋14.5%）で、2007年のマルハとニチロの経営統合以来、初めて300億円の壁を超えた節目の数字。経常利益は322億円（同＋3.7%）、純利益は233億円（同＋11.6%）。配当は1株当たり85円→110円に引き上げ（前期比＋29%）、5期連続増配。次期（2026年3月期）の会社予想は、営業利益270億円（前期比▲11.1%）と一転減益見通しだが、これは社名変更・本社移転・ブランド刷新などの企業変革投資（3年で150億円計画の初年50億円）を一括して販管費に計上するため。2025年12月末を基準日として1株→3株の株式分割を実施済み。\n\n**業績が動いた理由:** ①加工食品・ペットフードの好調：タイ工場から北米向けに輸出するペットフード事業の販売が大きく伸び、加工食品セグメント全体の営業利益は前期比で約40億円増。なぜなら、北米でペットフード需要が旺盛で、タイ生産による低コスト体制が競争力を発揮したから。②水産商事の資本効率改善：水産物の仕入れ・販売を担う水産商事部門が、在庫の適正化と資本効率を意識した売買管理を徹底したことで増益に転じた。③海外事業の大幅伸長：海外売上高は前期比＋17.7%の2,511億円、海外営業利益は同＋77.3%の140億円と急拡大。欧州でのサーモンを中心とした水産物販売が相場上昇の恩恵を受けた。④冷凍マグロ・ホタテの市況回復が利益を押し上げた。\n\n**株価が動いた理由:** 過去1年（概ね2024年〜2025年）で株価は約＋22〜24%上昇し、2025年9月時点で3,400〜3,700円台で推移。①最高益更新による再評価：営業利益が統合後最高の300億円超を達成したことで、長らくPBR0.8倍台と解散価値以下で放置されていたバリュー株として見直された。②大幅増配による配当利回り改善：1株85円→110円へ約29%の増配を発表したことで、配当利回りが3%台に改善。③株式分割・株主優待新設の発表（2025年11月）：1→3の株式分割と新社名記念の株主優待制度導入を発表したことで株価が年初来高値を更新。④中期経営計画・社名変更によるストーリー性：2025年3月に発表した中計「For the ocean, for life 2027」と「Umios」への社名変更が、「食の総合ソリューション企業」への変革を印象づけた。⑤売り出しによる一時下落（2024年8月）：東京海上などの金融機関8社が約325万株を売り出すと発表し需給悪化懸念から株価が一時▲7%急落したが、業績好調を受けて反発した。",
        "en_summary": "**Company overview:** Maruha Nichiro is Japan's largest integrated seafood and food company. It spans fishing and aquaculture, seafood wholesale trading, processed foods (frozen food, canned fish, fish sausages), pet food manufacturing (from a Thailand plant mainly for North America), and fine chemicals. Despite the \"fishing company\" image, the real profit engine is food ingredient distribution, processed foods, and overseas businesses. In March 2026 the company renamed itself \"Umios\" to signal a pivot toward becoming an ocean-centered food solutions company.\n\n**How did business move?** FY2025 (April 2024–March 2025): Revenue ¥1.079 trillion (+4.7%) — firmly above the ¥1 trillion mark. Operating profit ¥30.4 billion (+14.5%) — first time exceeding ¥30 billion since the 2007 Maruha-Nichiro merger. Net profit ¥23.3 billion (+11.6%). Dividend raised from ¥85 to ¥110 (+29% — fifth straight year of increases). For FY2026, management guides operating profit ¥27 billion (-11.1%), reflecting ¥5 billion in one-off transformation costs (name change, office relocation, rebranding); underlying ~¥32 billion (+5%). H1 FY2026 OP +16.6% YoY, tracking ahead. 1-for-3 stock split executed December 2025.\n\n**Why did business move this way?** (1) Pet food/processed foods boom — Thailand plant exports to North America surged on strong demand. (2) Seafood trading efficiency — inventory management discipline turned the unit profitable. (3) Overseas leap — revenue +17.7% to ¥251B, operating profit +77.3% to ¥14B, driven by European salmon market prices. (4) Recovery in tuna and scallop markets — North American and European buyers absorbed volumes diverted from China.\n\n**Why did the stock move this way?** Stock rose ~22–24% over the past year (¥3,400–3,700 range late 2025). (1) Record earnings re-rating: hitting OP above ¥30B post-merger prompted institutional re-evaluation of a stock long below book value (PBR ~0.8x). (2) Dividend jump pushed yield above 3%. (3) November 2025 stock split + shareholder gift announcement drove a year-high. (4) The medium-term plan and \"Umios\" rebrand added a growth narrative. (5) August 2024 institutional share sale of ~¥11.9B caused a temporary 7% drop, recovered as earnings proved resilient.",
        "sources": ["https://www.umios.com/jp/corporate/news_center/news_topics/20250512_jp_4Q_kessanntanshin.pdf","https://irbank.net/1333/pl","https://irbank.net/E00015/results","https://www.nikkei.com/article/DGXZQOFL270MU0X20C24A8000000/","https://www.nikkei.com/article/DGXZQOUC05A450V00C25A8000000/","https://www.nikkei.com/article/DGXZQOUC108DI0Q5A111C2000000/","https://kabutan.jp/news/marketnews/?b=n202511100987","https://www.umios.com/jp/corporate/news_center/news_topics/2025/03/24.html"],
        "notes": "FY2025 revenue ¥1,078,631M / OP ¥30,381M / NP ¥23,264M confirmed across irbank.net + official IR PDF + NNA/Nikkei. Dividend ¥85→¥110 confirmed multiple sources. FY2026 OP guidance ¥270B (-11.1%) confirmed. Stock split announcement November 2025 confirmed. Scallop recovery story flagged unverified for company-specific number. YoY +22–24% stock estimate from SimplyWallSt + Minkabu data; pre-split basis."
    },
    "1376": {
        "name": "Kaneko Seeds",
        "tab": "R+xS-",
        "bucket": "seed_agri_input_recovery",
        "rev_dir": "up", "rev_pct": "+3.1% (FY2026 guidance)",
        "op_dir": "up", "op_pct": "+25.7% (FY2026 guidance)",
        "net_dir": "up", "net_pct": "+25.0% (FY2026 guidance)",
        "stock_yoy_estimate": "Approx -13% from Oct 2025 peak (¥1,628 → ¥1,417 Jun 2026); broadly flat to modest decline YoY",
        "biz_classification": "Agricultural Seeds & Inputs / 農業種苗・農材",
        "jp_summary": "**会社概要:** カネコ種苗は1895年創業、群馬県前橋市に本社を置く農業関連の総合企業で、東証スタンダード市場に上場しています。主に4つの事業を持っています。①種苗事業：野菜・花・飼料作物の種子を自社で品種開発・生産・販売。②花き事業：花苗・球根・園芸用品を販売。③農材事業：農薬（殺虫剤・除草剤など）や被覆肥料を販売。④施設材事業：温室・養液栽培プラント・農業用資材を設計・施工・販売。4事業のうち農材事業が売上高の半分以上を占め、会社全体の収益を最も大きく左右するセグメントです。従業員695名（連結）、売上規模は約640〜660億円の中堅企業です。\n\n**業績の動き:** 直近の基準年となる2025年5月期（FY2025、2024年6月〜2025年5月）の通期連結実績は、売上高645億円（前期比＋4.7%）、営業利益15億1,200万円（同＋2.2%）、経常利益16億6,600万円（同＋6.1%）、純利益12億円（同＋1.9%）でした。続く2026年5月期は、2026年4月3日開示の第3四半期累計（9か月分）で売上高420億9,700万円（前年同期比＋2.1%）、営業利益4億7,500万円（同＋29.1%）、純利益3億7,000万円（同＋29.8%）。通期会社予想（変更なし）は売上高665億円（＋3.1%）、営業利益19億円（＋25.7%）、純利益15億円（＋25.0%）、年間配当1株48円を見込んでいます。\n\n**業績が動いた理由:** 2024年5月期に一度落ち込んだあと、2025年・2026年と回復・改善に向かっている主な理由は以下のとおりです。①農材事業の回復が主役：なぜかというと、コロナ禍後に農家の設備投資が抑制され農材需要が低迷していたのが正常化し、とくに茎葉除草剤・水稲剤の需要が拡大、さらに高利益率の製品へ品種構成がシフトしたことで、売上増と利益率改善が同時に進んだから。②施設材事業の利益急回復：FY2024は資材価格高騰で農家が設備投資を手控えたため利益が大きく落ち込んでいたが、FY2025には農業用温室・養液栽培関連の受注が戻り、営業利益が前期比8割超の増益となったから。③種苗事業のコスト増：人件費上昇と物流・保管設備の拡充により費用が増加し、売上は伸びても利益率が圧縮されたから。④花き事業の苦戦：コロナ禍のステイホーム需要が剥落したあと花苗・園芸材料の購入が落ち着き、事業全体で損益が赤字付近で推移しているから。\n\n**株価が動いた理由:** 過去約1年（2025年〜2026年6月）の株価は、おおむね1,310円〜1,628円の範囲で推移し、2025年10月に2年5か月ぶりの高値1,628円を付けたあと、2026年6月時点では1,417円前後まで落ち着いています。①2025年10月の急騰：Q1（2025年6〜8月期）の純利益が前年同期比2.8倍という想定外に大幅な増益となり、市場がポジティブサプライズとして好感したから。②高値後の調整：Q2・Q3と業績進捗が堅調ではあるものの通期会社予想が据え置きのままで上方修正が出ず、先取りした上昇分の一部が剥落したから。③低PBR・バリュー株としての底堅さ：PBR0.61倍という割安水準が長期投資家の下値買いを支えている。④アナリストカバレッジなし：IFIS集計では機関投資家のレーティングが現時点でゼロで、個人投資家中心の売買になっているため、決算発表前後に株価が大きく振れやすい。",
        "en_summary": "**Company overview:** Kaneko Seeds (founded 1895, TSE Standard) is an agricultural conglomerate headquartered in Maebashi, Gunma. It operates four segments: Seeds (vegetable/flower/forage crop seed breeding and sales), Floriculture (flower seedlings, bulbs, garden products), Agricultural Materials (pesticides, coated fertilizers, herbicides), and Facility Materials (greenhouse systems, hydroponics, agri-structures). Agricultural Materials is the largest segment (>50% of revenue), and the biggest profit driver. ~695 employees, revenue ~¥64–66 billion.\n\n**How did business move?** FY2025 (year ended May 2025): revenue ¥64.5B (+4.7%), operating profit ¥1,512M (+2.2%), ordinary profit ¥1,666M (+6.1%), net profit ¥1,200M (+1.9%). For FY2026, 9-month YTD through Feb 2026 showed revenue ¥42.1B (+2.1%), operating profit ¥475M (+29.1%), net profit ¥370M (+29.8%). Unchanged full-year guidance: revenue ¥66.5B (+3.1%), operating profit ¥1,900M (+25.7% — multi-year high target), net profit ¥1,500M (+25%), dividend ¥48.\n\n**Why did business move this way?** Recovery in FY2025–FY2026 driven by: (1) Agricultural Materials rebound — because demand for herbicides and rice-paddy pesticides recovered and the product mix shifted to higher-margin items. (2) Facility Materials profit recovery — because the FY2024 material-cost surge had suppressed farm-equipment investment; as pressure eased, greenhouse and hydroponics orders returned strongly (+80% segment profit). (3) Seeds segment margin compression — because rising labor costs and expanded logistics infrastructure added fixed costs. (4) Floriculture weakness — because the COVID-era gardening boom faded.\n\n**Why did the stock move this way?** Stock traded ¥1,310–¥1,628 over the past year, peaking in October 2025, currently around ¥1,417 (early June 2026). (1) October 2025 surge — because Q1 FY2026 net profit came in at 2.8× the prior year, a strong positive surprise. (2) Post-peak drift lower — because despite solid progress, management left full-year guidance unchanged (no upward revision). (3) Low valuation floor — because the stock trades at just 0.61× book value, attracting value-oriented buyers on dips. (4) No institutional analyst coverage — zero broker ratings means retail-driven trading and amplified swings on earnings.",
        "sources": ["https://irbank.net/E00004/pl","https://finance.yahoo.co.jp/quote/1376.T/performance","https://irbank.net/E00004/segment","https://www.nikkei.com/article/DGXZRST0597354S6A400C2000000/","https://simplywall.st/stocks/jp/food-beverage-tobacco/tse-1376/kaneko-seeds-shares/news/kaneko-seeds-tse1376-margin-improvement-supports-bullish-tur","https://kabuyoho.ifis.co.jp/index.php?action=tp1&sa=report_pbr&bcode=1376","https://irbank.net/1376/chart"],
        "notes": "Code 1376 confirmed as Kaneko Seeds. All P&L in ¥M (irbank initial fetch had unit-scale error — corrected). FY2025 revenue ¥64,509M (≈¥64.5B) confirmed Yahoo + IRBank. FY2026 9M YTD figures from official IR disclosure. Dividend ¥48 confirmed. Stock current ¥1,417 (Jun 5 2026) confirmed multiple sources. 52-week high ¥1,628 (Oct 2025) per Nikkei. No analyst ratings found (zero broker coverage per IFIS)."
    },
    "1377": {
        "name": "Sakata Seed",
        "tab": "R+xS+",
        "bucket": "seed_agri_input_recovery",
        "rev_dir": "up", "rev_pct": "+4.8%",
        "op_dir": "up", "op_pct": "+16.8%",
        "net_dir": "down", "net_pct": "-39.9% (FY2024 real-estate gain non-recurrence)",
        "stock_yoy_estimate": "Broadly flat to modest gain; 52-week range ¥3,310–¥4,630, current ~¥4,160 (approx. +5–10% YoY)",
        "biz_classification": "種苗メーカー / Seed & Agri-Inputs",
        "jp_summary": "**会社概要:** サカタのタネは横浜を本拠とする種苗メーカーで、野菜の種・花の種・球根・苗・農園芸資材の開発・生産・販売を手がける。国内トップシェアで、世界170か国以上に販売する世界6位クラスの種苗会社。売上の約8割が海外からで、とくにブロッコリーの世界シェアは約65%、トレニアという花の種では約70%を握る。北米・欧州・南米に現地法人を持ち、2013年以降はM&Aで海外基盤を急拡大してきた（2023年にはオランダのSana Seeds、ブラジルのIsla Sementesを買収）。決算期は5月末。\n\n**業績の動き:** 2025年5月期（FY2025）の連結業績は、売上高929億円（前期比＋4.8%：売上として過去最高）、営業利益123億円（前期比＋16.8%：営業利益も過去最高）、経常利益123億円（前期比＋10.7%）。ただし親会社純利益は97億円（前期比▲39.9%）と大幅減。配当は1株75円（前期比＋10円：5期連続増配）。純利益の大幅減は本業悪化ではなく、前期に「ガーデンセンター横浜」跡地の資産売却益という一時収入があった反動。本業の強さを示す営業利益は二ケタ増益だった。翌2026年5月期の会社計画は売上高955億円（＋2.9%）、営業利益110億円（▲10%）と保守的な見通し。しかし実際のQ1（2025年6〜8月）は営業利益が前年同期比＋63.5%、純利益は前年比3.2倍に急増し、翌期の上方修正期待が高まった状態。\n\n**業績が動いた理由:** 売上・営業利益が過去最高を更新した主な理由は三つ。①海外野菜種子の販売好調：ブロッコリー・カボチャ・トマト・スイカ・ヒマワリなどが北米・欧州・南米で伸びた。サカタは耐暑性・病害抵抗性に強い独自品種を持つため、気候変動への対応として農家から評価されているから。②円安効果：FY2025もドル高・ユーロ高が追い風になったから。③粗利率の改善：高付加価値品種へのシフトと価格転嫁が進んだから。純利益が前期比40%減になったのは、前期に不動産売却益（一時収入）があったが今期はそれがなかっただけで、本業は好調のまま。\n\n**株価が動いた理由:** 過去1年で見ると、株価は概ね3,300〜4,600円台のレンジで推移し、最終的には4,000〜4,200円前後。大きな動きは主に二回あった。①2025年10月の急騰：Q1好決算（営業利益＋63.5%、純利益3.2倍）の発表と同時に、会長の資産管理会社（持分17.56%）が約100万株を売却したいと表明したのに対し、会社が自社株TOBで株式を買い集めると発表したから。売りが出ても市場に流れないよう吸収し、需給悪化を防いだため株は急騰。②その後の上昇継続：野村証券が継続「Buy」で目標株価を5,700円→6,200円に引き上げるなどアナリスト支持が高まったから。PBRが0.9倍台と実力値より割安との見方が広がり、資本効率改善（自社株買い＋増配）の流れが評価された。",
        "en_summary": "**Company overview:** Sakata Seed is a Yokohama-based seed company that develops, produces, and sells vegetable seeds, flower seeds, bulbs, seedlings, and agricultural/horticultural supplies. It is Japan's largest seed company and roughly the 6th largest in the world, selling to over 170 countries. Around 80% of revenue comes from overseas. Holds ~65% of the global broccoli seed market and ~70% of the torenia flower seed market. Aggressive M&A expansion since 2013 (including Sana Seeds in the Netherlands and Isla Sementes in Brazil in 2023). Fiscal year ends May 31.\n\n**How did business move?** FY2025 (ended May 2025): record revenue ¥92.9B (+4.8%), record operating profit ¥12.3B (+16.8%), ordinary profit ¥12.3B (+10.7%). Net profit fell sharply to ¥9.7B (−39.9%) — but this reflects non-recurrence of a FY2024 real estate sale gain, not core business weakness. Dividend raised to ¥75 (+¥10 — five consecutive increases). For FY2026 the company guided conservatively (¥95.5B revenue, ¥11B OP). Actual Q1 FY2026 came in at OP +63.5% and net profit +222%, raising strong upward-revision expectations.\n\n**Why did business move this way?** Three main drivers: (1) Overseas vegetable seed strength — broccoli, pumpkin, tomato, watermelon, and sunflower performed well across major regions because Sakata's heat-tolerant and disease-resistant varieties are increasingly valuable as climate conditions worsen. (2) Weak yen added revenue through favorable currency translation. (3) Gross margin improvement through mix shift to premium varieties and successful price pass-through. Net profit fell only because FY2024 included a non-recurring real estate gain.\n\n**Why did the stock move this way?** Stock traded ¥3,310–¥4,630 over the year, ending around ¥4,160 — broadly flat to modestly higher. (1) October 2025 surge: Sakata announced blowout Q1 results alongside a self-tender offer (TOB) for its own shares — the chairman's asset-management company wanted to sell ~1M shares; instead of letting them hit the open market, Sakata bought them via TOB, absorbing supply. (2) Nomura raised target from ¥5,300 → ¥5,700 → ¥6,200 over 2025, signaling growing analyst conviction. At PBR ~0.9x the stock trades below book value despite strong fundamentals.",
        "sources": ["https://note.com/tousi525/n/nf5aaf923d075","https://stockanalysis.com/quote/tyo/1377/financials/","https://media.rakuten-sec.net/articles/-/50784","https://nikkeiyosoku.com/stock/rating/1377/","https://kabutan.jp/news/marketnews/?b=n202510080326","https://www.nikkei.com/nkd/disclosure/tdnr/20251003568195/","https://irbank.net/1377/pl"],
        "notes": "Revenue ¥92.9B + OP ¥12.3B confirmed across note.com/tousi525 and stockanalysis.com. NP -39.9% confirmed both; reason (FY24 real estate sale gain non-recurrence) confirmed. Dividend ¥75 confirmed. TOB details (¥3,285/share, ~1.1M shares, ~¥3.6B) confirmed Nikkei disclosure. Nomura target progression confirmed via nikkeiyosoku.com. Stock YoY estimate approximate."
    },
    "1379": {
        "name": "Hokuto",
        "tab": "R+xS-",
        "bucket": "domestic_food_shortage_beneficiary",
        "rev_dir": "up", "rev_pct": "+1.9%",
        "op_dir": "down", "op_pct": "~-12% (FY26 ~¥58B vs FY25 ¥66B)",
        "net_dir": "down", "net_pct": "~-2%",
        "stock_yoy_estimate": "Roughly flat to modest decline; 52-week range ¥1,690–¥2,123, current ~¥1,840–¥1,900",
        "biz_classification": "きのこ生産・販売 / Mushroom Production & Sales",
        "jp_summary": "**会社概要:** ホクトは長野県長野市に本社を置く、日本最大手のきのこ生産・販売会社です。ブナシメジ（しめじ）、エリンギ、マイタケなどを工場で大量生産し、全国のスーパーや食品メーカーに出荷しています。国内きのこ事業が売上の中心で、それ以外に北米・台湾・マレーシアなどに海外拠点を持ち、加工食品事業と化成品（きのこ栽培に使う素材）事業も手がけています。東証プライム上場で、時価総額は約600億円前後の中堅食品株です。\n\n**業績の動き:** 直近の確定期（2025年3月期）では、売上高831億円（前期比＋4.6%、過去最高水準）、営業利益66億円（前期比＋108%、ほぼ2倍に急増）、純利益44億円（前期比＋26%）と大幅な増益着地になりました。翌期の2026年3月期は、期初段階では「野菜相場の正常化で単価が下がる」との読みで営業利益35%減という保守的な計画を出しましたが、年度途中で状況が好転し、2025年11月に上方修正を実施。最終的な通期実績（2026年3月期）は売上高847億円（前期比＋1.9%、3期連続最高）、純利益は前期比約2%減の約43億円程度で着地した模様です。配当は年50円から55円へ増配しており、株主還元を強化しています。\n\n**業績が動いた理由:** ①野菜の連れ高できのこ単価が上昇——2024年夏から秋にかけて猛暑と長雨の影響でキャベツやレタスなど一般野菜が深刻な供給不足になり、スーパー全体の野菜値段が急騰しました。きのこは「工場栽培で天候に左右されず安定供給できる割安な代替品」として引き合いが増え、販売単価が計画より高く推移したため、2025年3月期の利益がほぼ倍増しました。②2024年10月の工場火災の影響が軽微だったから——長野県上田市のブナシメジ工場が全焼し（国内生産量の約7%相当）、当初は業績への打撃が懸念されましたが、他拠点の増産と保険金受取で実際の損失は限定的にとどまりました。③海外事業での新規顧客獲得と円安の追い風——北米市場での販売戦略が奏功し、円安が海外売上を円換算で押し上げました。④舟形マッシュルームの子会社化（2026年4月）——日本第3位のマッシュルーム生産会社を買収したことで、マッシュルーム分野への参入を強化。\n\n**株価が動いた理由:** 過去1年の52週レンジは1,690円〜2,123円で、2026年春時点では1,800〜1,900円台で推移しています。①2025年11月の上方修正発表が株価を支えた——予想を大きく上回る中間決算と同時に通期業績予想も引き上げたことで、「期初の保守的な計画より実力は高い」という再評価が起きました。②増配（50円→55円）が株主還元姿勢を示したから——配当を増やすことは「会社が今後の稼ぎに自信を持っている」サインとして受け取られた。③前期（2025年3月期）の高利益水準が「一時的な野菜高騰の特需」と市場に見なされ、株価の上値が抑えられた——前期の異例の高水準は野菜相場高騰という特殊要因の恩恵であり、それが正常化した後の実力（58億円程度）に見合った株価レンジへ収束した形です。④M&Aが成長期待を小幅に高めた——小規模な買収ですが、ポジティブに受け止められました。",
        "en_summary": "**Company overview:** Hokuto is Japan's largest mushroom producer, headquartered in Nagano. It grows Bunashimeji (beech mushrooms), Eringi (king oyster), and Maitake at scale in controlled indoor factories, selling to supermarkets and food manufacturers nationwide. Also has operations in North America, Taiwan, and Malaysia, plus smaller processed-food and chemical-products (mushroom cultivation materials) businesses. TSE Prime; market cap ~¥60 billion.\n\n**How did business move?** FY2025 (ended March 2025) confirmed actuals: revenue ¥83.1B (+4.6%), operating profit ¥6.63B (+108% — nearly doubled), net profit ¥4.44B (+26%). FY2026 (ended March 2026): the company initially guided for OP -35% on price normalization, but after an upward revision in November 2025, final results were revenue ¥84.7B (+1.9%, third consecutive record), net profit ~¥43B (-2%). Dividend raised from ¥50 to ¥55.\n\n**Why did business move this way?** (1) Mushroom prices rose because vegetables got expensive — 2024 summer heat waves and rain caused cabbage/lettuce supply shortfalls, lifting all supermarket vegetable prices. Shoppers shifted to mushrooms as a stable, factory-grown alternative. (2) A factory fire in October 2024 hurt less than feared — a Bunashimeji plant in Ueda, Nagano burned (~7% of national output), but other plants absorbed the shortfall and insurance proceeds offset the loss. (3) Overseas wins and a weak yen helped — North American sales grew, and currency translation boosted reported earnings. (4) Acquisition of Funagata Mushroom (April 2026) added button-mushroom capacity.\n\n**Why did the stock move this way?** 52-week range ¥1,690–¥2,123, settling in the ¥1,800–¥1,900 band. (1) November 2025 upward earnings revision lifted the stock — Q2 beat estimates and the full-year forecast was raised, drawing in buyers. (2) Dividend increase (¥50 → ¥55) attracted income investors. (3) Stock upside was capped because FY2025's profit spike was seen as a one-off tied to unusual vegetable prices unlikely to persist. (4) The Funagata Mushroom acquisition added modest growth optionality.",
        "sources": ["https://moneyworld.jp/news/PQV3974_ainews","https://finance.logmi.jp/articles/381641","https://www.nikkei.com/article/DGXZQOCC145C60U5A510C2000000/","https://www.nikkei.com/nkd/disclosure/tdnr/20260408599838/","https://www.tipranks.com/news/company-announcements/hokuto-lifts-full-year-profit-outlook-on-strong-mushroom-sales-and-fx-gains","https://irbank.net/1379/pl","https://kabutan.jp/stock/finance?code=1379"],
        "notes": "FY2025 actuals (Rev ¥83.1B / OP ¥6.63B / NP ¥4.44B) confirmed across IRBank, Moneyworld/QUICK, Logmi Finance, Nikkei disclosure. FY2026 revenue ¥84.7B confirmed multiple sources. FY2026 NP ~¥43B (-2%) per Nikkei DGXZQOCC145C60U5A510C2000000 — flagged as approximate (Nikkei headline 'NP 30% increase' refers to Nov 2025 upward revision vs initial guidance, not vs prior-year actual). Factory fire (Oct 2024 Ueda) confirmed; Funagata acquisition (Apr 2026) confirmed Nikkei TDnet. Dividend ¥50→¥55 confirmed."
    },
    "1380": {
        "name": "Akikawa Bokuen",
        "tab": "R+xS-",
        "bucket": "organic_subscription_microcap_recovery",
        "rev_dir": "up", "rev_pct": "+4.1%",
        "op_dir": "up", "op_pct": "turnaround (prior ▲¥3M → +¥143M)",
        "net_dir": "down", "net_pct": "-25% (impairment charge ¥143M)",
        "stock_yoy_estimate": "Roughly flat YoY (~¥990–1,005 now vs ~¥1,009 a year ago; 52W range ¥982–¥1,094, intra-year peak ~¥1,250)",
        "biz_classification": "有機農畜産・産直宅配 / Organic Farm-to-Home Subscription",
        "jp_summary": "**会社概要:** 秋川牧園（山口県）は1972年創業の農畜産・食品会社で、鶏肉・豚肉・牛肉・卵・牛乳・野菜・冷凍加工食品など約2,000品目を自社農場から消費者に直送する「産直宅配」をメインビジネスにしている。化学合成農薬不使用の野菜・抗生物質不使用飼育の鶏肉など「安心・安全」にこだわった商品を会員向け定期宅配サービスで届けており、スーパーでは買えない付加価値をウリにしている。東証スタンダード上場で時価総額は約42億円の小型株。セグメントは「生産・卸売事業」（売上の約81%）と「直販事業」（約19%）の2本柱。\n\n**業績の動き:** 2026年3月期（2025年4月〜2026年3月）の確定業績（2026年5月15日発表）は、売上高82億83百万円（前期比＋4.1%、4年連続増収）、営業利益1億43百万円（前期は▲3百万円の赤字から黒字転換）、経常利益1億86百万円（前期比＋261%、会社自身の予想1億20百万円を55%上回る大幅超過達成）、純利益2,100万円（前期比▲25%）。純利益だけ減っているのは、直販事業と中国子会社の資産を1億43百万円分だけ「回収見込みなし」として帳簿上切り下げた減損損失を特別損失として計上したため。経常レベルでは明確に回復している。配当は1株10円（前期と同額）を維持。\n\n**業績が動いた理由:** 2023〜2025年3月期の3期連続減益の主因は、①円安による配合飼料価格の高止まり（鶏や豚のエサ代は輸入穀物依存が高いため、円安が製造コストを直撃した）、②2023年11月に稼働した新直販物流センターの減価償却負担が固定費を押し上げたこと、③宅配食品の需要がコロナ禍の特需の反動で一時的に落ち込んだこと、が重なったから。2026年3月期に回復できた主な理由は、①冷凍加工食品の販売が好調で売上がしっかり伸びたこと、②数度にわたる価格改定（値上げ）の効果が利益に乗ってきたこと、③中国子会社（秋川牧園農業有限公司）を2024年3月に連結に取り込んだことで鶏肉生産・販売の規模が広がったこと。一方で直販事業・中国子会社の採算が想定を下回っていたため、これらの資産を減損し純利益を押し下げた。\n\n**株価が動いた理由:** 過去1年の株価は概ね982〜1,094円のレンジで、直近は990〜1,005円前後で推移しており、前年同期比ではほぼ横ばいとなっている。52週を通じては最大1,250円近くまで上昇した局面があった。株価が一時高値を付けたのは、四半期ごとの決算で経常利益が会社予想を大幅に上回る進捗を示し続けたため。その後株価が戻ったのは、2026年5月の通期決算発表で経常利益こそ予想超過だったが、減損損失計上により純利益が前期を下回ったこと、また翌2027年3月期の見通しが利益「減少」方向と伝わったことで、期待先行で積み上がっていたポジションが巻き戻されたから。時価総額42億円の薄商い小型株のため、わずかな期待の変化でも株価の振れ幅が大きくなりやすい。アナリストのレーティング・目標株価は確認できず（カバレッジなし）。",
        "en_summary": "**Company overview:** Akikawa Bokuen (Yamaguchi Prefecture, est. 1972) is a vertically integrated organic farm-to-home food company. It raises antibiotic-free chickens and pesticide-free vegetables on its own farms, then ships them directly to subscriber households — about 2,000 product lines including chicken, pork, beef, eggs, dairy, vegetables, and frozen prepared foods. Think of it as a premium organic subscription that actually owns and runs the farms. TSE Standard; market cap ~¥4.2 billion (micro-cap). Two segments: Production & Wholesale (~81%) and Direct Sales (~19%).\n\n**How did business move?** FY2026 (ended March 2026), announced May 15 2026: Revenue ¥8,283M (+4.1% YoY — 4th straight year of top-line growth), Operating Profit ¥143M (vs. a ¥3M operating loss in FY2025 — clean swing back to black), Ordinary Profit ¥186M (+261% YoY, 55% above the company's own ¥120M forecast — a meaningful beat), Net Income ¥21M (-25% YoY). Net income fell because the company booked ¥143M in impairment losses on direct-sales and Chinese subsidiary assets. Below the operating line the business is clearly recovering; at net income the write-down muddied the picture. Dividend held flat at ¥10.\n\n**Why did business move this way?** Three years of consecutive profit declines had three causes: (1) feed costs surged because Japan imports most animal feed grain — yen weakness drove input costs higher; (2) a new direct-sales logistics center opened in November 2023 added heavy depreciation before revenue benefits materialized; (3) post-COVID hangover as lockdown subscribers cancelled. FY2026 recovery: (1) frozen processed foods grew; (2) multiple price hikes finally flowed through; (3) the Chinese subsidiary was consolidated in March 2024, adding revenue. The impairment reflects honest write-down of underperforming assets.\n\n**Why did the stock move this way?** 52-week range ~¥982–¥1,094, current ~¥990–1,005, broadly flat YoY. Intra-year peak ~¥1,250. Stock rose toward the peak because quarterly earnings tracked well ahead of company targets — by Q3 the company had hit 103% of full-year OP forecast, pricing in an optimistic recovery. Stock then retreated because the full-year actual delivered a net income decline via the impairment surprise, and FY2027 guidance points to profits declining again. Thinly traded micro-cap amplifies sentiment swings. No broker coverage found.",
        "sources": ["https://irbank.net/E00344/pl","https://finance.yahoo.co.jp/quote/1380.T/financials","https://kabuyoho.jp/reportTop?bcode=1380","https://strainer.jp/companies/8/performance","https://www.nikkei.com/article/DGXZRST0550681U5A510C2000000/","https://finance.yahoo.co.jp/quote/1380.T","https://www.akikawabokuen.com/ir-settlement/"],
        "notes": "FY2026 actuals (Rev ¥8,283M / OP ¥143M / Ordinary ¥186M / NP ¥21M) confirmed across IRBank + Yahoo Finance + Strainer + kabuyoho. Operating turnaround from FY25 ¥-3M to FY26 ¥+143M confirmed. Impairment ¥143M (direct sales + China subsidiary) confirmed Yahoo Finance description. Stock current ¥990–1,005 (Jun 5–7 2026 Yahoo); year-ago proxy ¥1,009 from futunn/investing.com. No analyst coverage found."
    },
    "1381": {
        "name": "Axyz",
        "tab": "R+xS+",
        "bucket": "domestic_food_shortage_beneficiary",
        "rev_dir": "up", "rev_pct": "+2.3%",
        "op_dir": "up", "op_pct": "+35.1%",
        "net_dir": "up", "net_pct": "+38.8%",
        "stock_yoy_estimate": "+57% over 2025 calendar year (¥2,643 end-2024 → ¥4,145 end-2025; currently ~¥3,770 Jun 2026)",
        "biz_classification": "食鳥処理・鶏肉加工 / Poultry Processing & Chicken Products",
        "jp_summary": "**会社概要:** アクシーズ（株式会社アクシーズ、東証スタンダード1381）は鹿児島を本拠とする鶏肉の一貫生産・加工会社です。飼料の製造から種鶏の飼育、雛の生産、ブロイラーの肥育、食鳥処理・加工食品の製造・販売まで自社で一連の工程をこなす「川上から川下まで自分でやる」垂直統合型のビジネスです。売上の84%を占める食品事業（唐揚げ・チキンナゲットなど鶏肉加工品の製造販売）を軸に、残り14%をKFCやピザハットのフランチャイズ店舗運営、残り2%を鶏舎廃棄物を使った再生可能エネルギー事業が担います。主な得意先はフードリンク（売上の21%）と日冷フレッシュ（18%）で、業務用・加工用の鶏肉を大口で供給しています。時価総額は約212億円の中小型株です。\n\n**業績の動き:** 直近の確定済み決算は2025年6月期通期です。売上高264億円（前期比+2.3%増）、営業利益21億円（+35.1%増、利益は売上以上に大きく伸びた）、純利益17億円（+38.8%増）となり、増収大幅増益でした。その翌期である2026年6月期は第3四半期時点で売上高218億円（前年同期比+11.8%）・営業利益29億円（+122%増、前の年の倍以上）を達成しており、会社は通期予想を上方修正しました。修正後の通期ガイダンスは売上高288億円（+9%）・営業利益34億円（+60%）・純利益24億円（+40%）・1株配当112.5円を見込みます。\n\n**業績が動いた理由:** 主な理由は3つです。①鶏肉相場の上昇：2024年末から2025年にかけて国内外で鳥インフルエンザが相次いで発生し、輸入鶏肉（日本の輸入の約7割を占めるブラジル産）の供給が絞られたため国内の鶏肉相場が大きく上昇しました。アクシーズは国内自社生産が主軸なので、高い相場価格をそのまま売上単価の上昇として享受できました。②飼料コストの低下：前期まで収益を圧迫していた飼料原料（トウモロコシ・大豆ミールなど）の仕入コストが2025年に入って低下に転じたため、売上原価が下がり利益率が大幅に改善しました。③KFC事業の拡大：2025年にKFC店舗を新規出店し売上を伸ばしました。\n\n**株価が動いた理由:** 株価は2024年末の約2,643円から2025年末の約4,145円へと1年間で+57%上昇しました。背景は以下の3点です。①業績の大幅上方修正：飼料費低下と鶏肉相場の上昇が同時に起きたことで利益が想定以上に改善し、会社が2026年6月期の予想を大幅上方修正したことが、投資家の買いを呼びました。②鶏肉需給のひっ迫という追い風テーマ：鳥インフルエンザ問題が広がるなかで国内鶏肉生産者への注目が高まりました。③バリュエーションの割安感：PERが10倍前後、PBRが1倍を下回る水準だったため、業績改善が確認されたタイミングで割安解消の買いが入りやすい状態でした。2026年に入って株価が一服しているのは、鶏肉相場の先行き不透明感と市場全体の地合い悪化が重なったためとみられます。",
        "en_summary": "**Company overview:** Axyz Co., Ltd. (TSE Standard, 1381) is a vertically integrated poultry company headquartered in Kagoshima. It controls the entire chicken supply chain in-house — from feed manufacturing and breeding through to processing and selling finished products like karaage fried chicken and nuggets. About 84% of revenue comes from the food business (processed chicken products), 14% from KFC and Pizza Hut franchise restaurants, and 2% from a renewable-energy operation. Top customers FoodLink (21%) and Nicherei Fresh (18%) account for ~39% of sales combined. Market cap ~¥21.2 billion (small-cap).\n\n**How did business move?** FY2025 (July 2024 – June 2025): Revenue ¥26.4B (+2.3%), Operating profit ¥2.12B (+35.1%), Net profit ¥1.72B (+38.8%). FY2026 9-month YTD (to March 2026): Operating profit reached ¥2.9B, more than double the same period a year ago (+122%). The company twice revised full-year FY2026 forecast upward; latest guidance calls for revenue ¥28.8B (+9%), OP ¥3.4B (+60%), NP ¥2.4B (+40%), dividend ¥112.5.\n\n**Why did business move this way?** Three things happened at once. (1) Chicken prices rose sharply — avian influenza outbreaks in 2024–25 disrupted imported chicken supply (Brazil supplies ~70% of Japan's imports), so domestic market prices climbed, and Axyz — as a domestic producer — sold at those higher prices. (2) Feed costs fell — corn and soybean meal prices came down in 2025, cutting Axyz's biggest input cost and dramatically widening margins. (3) KFC store expansion added revenue from new outlets.\n\n**Why did the stock move this way?** The stock rose ~57% during calendar 2025 (¥2,643 → ¥4,145), peaking at ¥4,600 in January 2026, before pulling back to ~¥3,770 as of June 2026. (1) Successive upward profit revisions — costs dropped and chicken prices rose simultaneously, drawing in investors as the company kept upgrading earnings forecasts. (2) Thematic buying around the avian flu story — domestic chicken producers attracted attention as poultry supply disruption concerns spread. (3) Cheap valuation unwinding — Axyz was trading below book value (PBR <1x) and at low P/E; once improved earnings became clear the stock re-rated upward. The 2026 pullback reflects uncertainty about whether the favorable chicken market will hold.",
        "sources": ["https://finance.yahoo.co.jp/quote/1381.T","https://finance.yahoo.co.jp/quote/1381.T/financials","https://irbank.net/E00009","https://kabutan.jp/stock/news?code=1381&b=k202504250074","https://www.nikkei.com/nkd/disclosure/tdnr/20250425523435/","https://www.nikkei.com/nkd/disclosure/tdnr/20250807535495/","https://kitaishihon.com/company/1381/business","https://simplywall.st/stocks/jp/food-beverage-tobacco/tse-1381/axyz-shares"],
        "notes": "Code 1381 confirmed as Axyz. All yen in 億円 (100M yen). FY2025 (Rev ¥264.26億 +2.3% / OP ¥21.21億 +35.1% / NP ¥17.20億 +38.8%) confirmed by Nikkei TDnet + Yahoo + kitaishihon. FY2026 revised guidance (Rev ¥288億 / OP ¥34億 +60% / NP ¥24億 +40%) sourced from Yahoo Finance financials page (April 2026 upward revision). Stock: ¥3,770 (Jun 5 2026), 52wk high ¥4,600 (Jan 22 2026), low ¥3,380 (Mar 23 2026). Dividend ¥112.5/share. No analyst ratings/targets found."
    },
}

OUT.write_text(json.dumps(DATA, ensure_ascii=False, indent=2), encoding='utf-8')
json.loads(OUT.read_text(encoding='utf-8'))  # validate
print(f"Wrote {OUT.name}")
print(f"Total entries: {len([k for k in DATA if k != '_meta'])}")
tabs = [DATA[k].get('tab') for k in DATA if k != '_meta']
buckets = [DATA[k].get('bucket') for k in DATA if k != '_meta']
print(f"Tabs: R+xS-={tabs.count('R+xS-')}, R+xS+={tabs.count('R+xS+')}")
print(f"Buckets: {sorted(set(buckets))}")
